config/routes.rb
Rails.application.routes.draw do

  get 'user/edit_info'

  post 'user/update_info'
  post 'user/sent_code'
  post 'user/valid_phone'

  devise_for :users
  resources :orders

  resources :line_items

  resources :carts

  resources :products

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart
  include Mongoid::Document
  include Mongoid::Timestamps
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = self.line_items.where(product_id: product_id).first
    if current_item != nil
      current_item.quantity += 1
    else
      current_item = line_items.new product_id: product_id
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find params[:id]
    # rescue Mongoid::Errors::DocumentNotFound
      # logger.error "Attempt to access invalid cart #{params[:id]}"
      # redirect_to store_url, notice: "不可用的购物车"
    # else
      respond_to do |format|
        format.html # show.html.haml
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = current_cart
    product = product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      # begin
        @cart = Cart.find(params[:id])
      # rescue Mongoid::Errors::DocumentNotFound
      #   logger.error "Attempt to access invalid cart #{params[:id]}"
      #   redirect_to store_path, notice: 'Invalid cart'
      # end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
- unless cart.line_items.empty?
  .cart_title 购物车
  %table.table
    = render(cart.line_items)

    %tr.total_line
      %td{colspan: 2} 总价
      %td.total_cell=number_to_currency cart.total_price

  = button_to '去支付', new_order_path, method: 'get', class: 'btn btn-primary'
  = button_to '清空购物车', cart, method: 'delete',data: { confirm: "确认清空购物车?" }, class: "btn btn-warning"

app/views/carts/_form.html.haml
= form_for(@cart) do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2
        = pluralize(@cart.errors.count, "error")
        prohibited this cart from being saved:
      %ul
        - @cart.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/carts/edit.html.haml
%h1 Editing cart
= render 'form'
= link_to 'Show', @cart
|
\#{link_to 'Back', carts_path}

app/views/carts/index.html.haml
%h1 购物车列表

%table.table.table-striped
  %thead
    %tr
      %th{colspan: 3}
  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart
= render 'form'
= link_to 'Back', carts_path

app/views/carts/show.html.haml
%p#notice
  = notice
%h2
  Your Pragmatic Cart
%table.table.table-striped.table-hover
  = render(@cart.line_items)

  %tr.text-right
    %td{colspan: 2} Total
    %td
      = number_to_currency(@cart.total_price)

%br
= button_to 'Empty cart',  @cart, method: :delete, confirm: 'Are you sure', class: 'btn btn-primary'

= link_to 'Edit', edit_cart_path(@cart)
|
= link_to 'Back', carts_path